// Code generated by "stringer -type=MsgType"; DO NOT EDIT

package server

import "fmt"

const _MsgType_name = "RunChecksAdvertiseMsgsRequestMsgs"

var _MsgType_index = [...]uint8{0, 9, 22, 33}

func (i MsgType) String() string {
	if i < 0 || i >= MsgType(len(_MsgType_index)-1) {
		return fmt.Sprintf("MsgType(%d)", i)
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
